import assert from 'node:assert/strict';
import {readFile,readdir} from 'node:fs/promises';
import {normalize,validateInvitation,eventDate,calendar,safeURL,defaults} from '../dist/model.js';
import {onRequest as invitations} from '../functions/api/invitations/[[slug]].js';
import {onRequest as rsvp} from '../functions/api/rsvp/[[slug]].js';
import {onRequest as media} from '../functions/api/media/[[name]].js';
const data=normalize(defaults);
assert.equal(eventDate(data).toISOString(),'2027-02-14T02:00:00.000Z');
assert.match(calendar(data),/DTSTART:20270214T020000Z/);
assert.equal(safeURL('javascript:alert(1)'), '');
assert.equal(safeURL('https://example.com/photo.jpg'),'https://example.com/photo.jpg');
assert.equal(normalize({...data,volume:100}).volume,1);
assert.equal(normalize({...data,theme:'<script>'}).theme,'royal');
assert.equal(normalize({...data,gallery:Array(20).fill('https://example.com/p.jpg')}).gallery.length,12);
assert.equal(normalize({...data,musicUrl:'data:audio/mpeg;base64,SUQz'}).musicUrl,'data:audio/mpeg;base64,SUQz');
assert(validateInvitation({...data,slug:'../../admin'}).length);
assert(validateInvitation({...data,hero:'data:image/png;base64,aaaa'},{published:true}).length);
const secret='a'.repeat(64),origin='https://undangan.sumsstudio.id';let payload=null;let storedRsvp=null;
const env={ADMIN_TOKEN:secret,DB:{prepare(sql){return {bind(...args){return {async first(){return payload?{payload}:null;},async run(){if(sql.startsWith('INSERT INTO invitations'))payload=args[1];if(sql.startsWith('INSERT INTO rsvps'))storedRsvp=args;return {success:true};},async all(){return {results:[]};}};}};}}};
const req=(method,body,authorization=secret,requestOrigin=origin)=>new Request(origin+'/api/invitations/'+data.slug,{method,headers:{'Content-Type':'application/json','Origin':requestOrigin,Authorization:'Bearer '+authorization},...(body?{body:JSON.stringify(body)}:{})});
assert.equal((await invitations({request:req('PUT',data,'wrong'),env,params:{slug:data.slug}})).status,401);
assert.equal((await invitations({request:req('PUT',data,secret,'https://evil.example'),env,params:{slug:data.slug}})).status,401);
assert.equal((await invitations({request:req('PUT',data),env,params:{slug:data.slug}})).status,200);
const loaded=await invitations({request:req('GET'),env,params:{slug:data.slug}});assert.equal((await loaded.json()).bride,data.bride);
assert.equal((await invitations({request:req('PUT',{...data,slug:'bad/slug'}),env,params:{slug:data.slug}})).status,400);
assert.equal((await invitations({request:req('GET'),env:{},params:{slug:data.slug}})).status,503);
assert.equal((await rsvp({request:req('GET',null,'wrong'),env,params:{slug:data.slug}})).status,401);
assert.equal((await rsvp({request:req('POST',{name:'Test User'}),env,params:{slug:data.slug}})).status,503);
const originalFetch=globalThis.fetch;globalThis.fetch=async()=>new Response(JSON.stringify({success:true,hostname:'undangan.sumsstudio.id'}),{headers:{'Content-Type':'application/json'}});
const confirmed=await rsvp({request:req('POST',{name:'Test User',attendance:'yes',guests:2,message:'Selamat!',id:crypto.randomUUID(),turnstileToken:'valid-token'}),env:{...env,TURNSTILE_SECRET:'test-only'},params:{slug:data.slug}});
assert.equal(confirmed.status,200);assert.equal(storedRsvp[2],'Test User');assert.equal(storedRsvp[4],2);
globalThis.fetch=async()=>new Response(JSON.stringify({success:true,hostname:'evil.example'}),{headers:{'Content-Type':'application/json'}});
assert.equal((await rsvp({request:req('POST',{turnstileToken:'test'}),env:{...env,TURNSTILE_SECRET:'test-only'},params:{slug:data.slug}})).status,403);globalThis.fetch=originalFetch;
let storedMedia;const mediaEnv={...env,MEDIA:{async put(name,body,metadata){storedMedia={name,body,metadata};}}};
const mediaReq=new Request(origin+'/api/media/',{method:'POST',headers:{Origin:origin,Authorization:'Bearer '+secret,'Content-Type':'image/png'},body:new Uint8Array([137,80,78,71,13,10,26,10,0,0,0,0])});
assert.equal((await media({request:mediaReq,env:mediaEnv,params:{}})).status,201);assert.equal(storedMedia.metadata.httpMetadata.contentType,'image/png');
const forged=new Request(origin+'/api/media/',{method:'POST',headers:{Origin:origin,Authorization:'Bearer '+secret,'Content-Type':'image/png'},body:'<html>not an image</html>'});assert.equal((await media({request:forged,env:mediaEnv,params:{}})).status,400);
const html=await readFile('dist/index.html','utf8'),js=await readFile('dist/app.js','utf8'),css=await readFile('dist/style.css','utf8');
for(const m of html.matchAll(/(?:src|href)="(\/[^"#]+)"/g)){if(m[1]!=='/')await readFile('dist'+m[1]);}
for(const id of ['studio','invitation','editor','lightbox','editorForm','publish','toast'])assert(html.includes(`id="${id}"`));
assert(css.includes('prefers-reduced-motion'));assert(js.includes('Konfirmasi ini tidak dikirim'));assert(js.includes('textContent'));assert(!html.includes('eventText'));
try{const workflows=await readdir('.github/workflows');assert.equal(workflows.length,0,'Invitation must not consume GitHub Actions');}catch(err){if(err.code!=='ENOENT')throw err;}
console.log('PASS: WITA/calendar, safe URLs, theme/media limits, admin authorization, origin checks, invitation persistence, RSVP protection/storage, media validation, static assets, reduced motion, no Actions workflows.');
